name: autodeploy

on:
  push:
    branches: [main]

jobs:
  gh-deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Add key to allow access to repository
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "${{ secrets['FAQDEPLOYER'] }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat <<EOT >> ~/.ssh/config
          Host github.com
          HostName github.com
          IdentityFile ~/.ssh/id_rsa
          EOT
      - name: Release to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
        run: 
          git config --global user.email "actions@github.com"
          git config --global user.name "bumblefudge"
          git clone https://github.com/decentralized=identity/faq --depth 1 ../faq
          if [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm install spec-up
          npm run render
          \cp -r docs/index.html index.html
          git add -A
          git commit -a -m "to push index.html-->gh-pages (GH Action)"
          git push origin main
